### ISSUE TITLE
Generating attribute values file is different from the example file uploaded

### ISSUE THREAD

**Issue by MajlindaLlugiqi** [rconfalonieri/trepan_reloaded#2]
While trying to generate files that are needed for trepan using `writeTrepanAttributesValuesFile` in FFN from `generate-trepan-network.py` (or ‘demoutils.py’ which has the same `generate_trepan_input_descriptors_and_nominals`), I am generating an .attr.value file which is different from the files in the examples uploaded. In the examples uploaded there is some kind of mapping with the ontology file like `age R  hasAge` while I am getting `age R age`. Is there any other part of the code used to generate these files?

Moreover the invoke_class that uses the java library 'libs/ontology-wrapper.jar' is not used anywhere, is the information content calculated some other way, or I am missing something?

**Comment by rconfalonieri** [comment]
You are right in saying that the ontology-wrapper.jar is not currently used. It could be in principle used from the Trepan Reloaded code, but since the information content of the concepts in the ontology can be calculated once, the values are pre-computed and stored in the .onto file. 
Calling Java from C code is not great and this integration was not investigated properly.
As far as the .attr.values is concerned I need to check -> the file is automatically generated but the mapping is manually done :(

**Comment by MajlindaLlugiqi** [comment]
Thank you for your swift reply.

So did you use the `invoke_class` to calculate information content and generate .onto file, or did you create .onto file from somewhere else?

**Comment by MajlindaLlugiqi** [comment]
Thank you for your swift reply.

I managed to get the code running inside of the main.c calling invoke_class but unfortunately without any output.

I tried running the wrapper-ontology.jar outside of the project using Java, and managed to get it running, but only using default arguments and it is only creating an empty heart.onto file.

Therefore, I wanted to ask, is there any source or documentation where I could look up the usage/find more information of this ontology-wrapper.jar?

**Comment by MajlindaLlugiqi** [comment]
Thank you for your swift reply.

I managed to get the code running inside of the `main.c` calling `invoke_class` but unfortunately without any output.

I tried running the `wrapper-ontology.jar` outside of the project using Java, and managed to get it running, but only using default arguments and it is only creating an empty `heart.onto` file.

Therefore, I wanted to ask, is there any source or documentation where I could look up the usage/find more information of this `ontology-wrapper.jar`?

**Comment by rconfalonieri** [comment]
you are right, I also tried `ontology-wrapper.jar` and it looks for a predefined .onto and .jar file. 
Good news is that I found the source code of the ontology-wrapper, bad news is that I have to spend a bit of time to let it compile to create a new jar (I changed several laptops since the time I wrote the code).

**Comment by rconfalonieri** [comment]
I modified the `ontology-wrapper.jar` (please pull). Now it expects two parameters as inputs, the first one is a .onto file and the second one is the ontology file.  The `.onto` file contains the list of (dataset) attributes (one per line) with a corresponding concept (if any) in the ontology. The information content is computed for all the concepts in the ontology, then the onto file is scanned. The code re-writes the content of the onto file by setting, e.g., 'Education 1 0.6703046630801344' if a concept Education exists in the ontology, and the corresponding information content is added. Otherwise a 0 will be set.

I cannot remember now if the onto file was generated by the python script when all Trepan files were generated. If not it should because it contains the list of attributes that are to be mapped against the onto.

I will also upload the code of the ontology wrapper, it is a Maven project: [git@github.com:rconfalonieri/trepan_reloaded_ontology_wrapper.git](git@github.com:rconfalonieri/trepan_reloaded_ontology_wrapper.git)

Sorry for the incomplete pieces..

**Comment by MajlindaLlugiqi** [comment]
Thank you for your response and explanation; it was very helpful.

As far as I can tell from my experiments, the `.onto` file is not generated by the python script. Maybe it is done manually. And after I put the concepts and (1 or 0) manually into `.onto` file, the generated `information content` for some reason is different from your results. For every concept my calculated information content is exactly `1 - your_result`.

For example `heart_dataset`: 
        your result :`hasAge 1 0.20584683246043445`
        my result :`hasAge 1 0.7941531675395656`

**Comment by rconfalonieri** [comment]
Right, thanks for checking.
Then it would be definitely good if the .onto file were generated in the TrepanReloaded Python preparation script. Will try to do that. 

The code would need to be refactored but I never had the time to do that. 
ps: Are you patching it already?

As far as the information content is concerned, its definition is `IC of a concept C can be defined as = 1 - log(|S(C)| + 1) / nr_subconcepts` but the .onto file contains `1-IC` (this because the formula of the modified information gain in the paper uses an inverse). 

I committed the changes to the Java code.

**Comment by MajlindaLlugiqi** [comment]
I have not tried to refactor the code, I was trying to reproduce and understand the experiment first.

Thank you very much for your explanation.
